# Generated by Django 3.2.7 on 2021-10-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPAT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.CharField(choices=[('E', 'Economica'), ('J', 'Ejecutiva')], default='E', max_length=1, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='fare',
            name='category',
            field=models.CharField(choices=[('E', 'Economica'), ('J', 'Ejecutiva')], default='E', max_length=1, verbose_name='Category'),
        ),
    ]
